name: US & International News Twitter Stats Tracker

on:
  schedule:
    - cron: "0 13 * * *"  # 8am EAST
    - cron: "0 19 * * *"  # 2pm EAST
    - cron: "0 1 * * *"   # 8pm EAST
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim

    permissions:
      contents: write 
      pull-requests: write
    
    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Determine Token
        id: token-rotation
        run: |
          python .github/scripts/determine_token.py
        env:
          X_BEARER_TOKEN_1: ${{ secrets.X_BEARER_TOKEN_1 }}
          X_BEARER_TOKEN_2: ${{ secrets.X_BEARER_TOKEN_2 }}
          X_BEARER_TOKEN_3: ${{ secrets.X_BEARER_TOKEN_3 }}

      - name: Check if we have a valid token
        if: ${{ steps.token-rotation.outputs.token == '' }}
        run: |
          echo "No token available. Skipping this run."
          exit 0

      - name: Run script
        env:
          X_BEARER_TOKEN: ${{ steps.token-rotation.outputs.token }}
        run: |
          echo "Using token: $X_BEARER_TOKEN"
          python src/news_tracker_run.py

      - name: Commit & push changes
        run: |
          cd $GITHUB_WORKSPACE

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git diff-index --quiet HEAD || git commit -m "Update next batch of stats $(date +'%Y-%m-%d %H:%M:%S')"
          git push